name: review
on: [pull_request]
jobs:
  checkpatch:
    name: checkpatch review
    runs-on: ubuntu-latest
    steps:
    - name: 'Calculate PR commits + 1'
      run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> $GITHUB_ENV
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ env.PR_FETCH_DEPTH }}
    - name: Run checkpatch review
      uses: webispy/checkpatch-action@v9
  make:
    name: compilation test
    strategy:
      matrix:
        gcc-version: [7, 8, 9, 10, 11]
    runs-on: ubuntu-latest
    steps:
    - uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: 'Generate compiling configurations'
      run: ./autogen.sh && ./configure
    - name: 'Make'
      run: make -j$(nproc)